apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # CRD from helm chart is not installed automatically
  # https://github.com/argoproj/argo-cd/issues/3784
  - github.com/traefik/traefik-helm-chart/traefik/crds?ref=v39.0.0
  - credentials.yaml
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 39.0.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
