apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-cert
spec:
  secretName: local-tls
  dnsNames:
    - "*.home.arpa" # Wildcard must be quoted
  issuerRef:
    name: selfsigned-issuer
