apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: istio
  # # defaultScope requires Experimental channel
  # defaultScope: All
  # For future L4 routing when gateway service must be reachable
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: gateway.home.arpa
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same # Only allow https-redirect route to attach
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
        - name: local-tls
    allowedRoutes:
      namespaces:
        from: All
