apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: adguard-credentials
  data:
    - secretKey: username
      remoteRef:
        key: adguard_user
        property: username
    - secretKey: password
      remoteRef:
        key: adguard_user
        property: password
