apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aPatchyDev/homelab.git
    targetRevision: main
    path: kubernetes/apps/network-test
  destination:
    server: https://kubernetes.default.svc
    namespace: network-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
