apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aPatchyDev/homelab.git
    targetRevision: main
    path: kubernetes/apps/storage-test
  destination:
    server: https://kubernetes.default.svc
    namespace: storage-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
