apiVersion: v1
kind: Service
metadata:
  name: lb-test
  annotations:
    metallb.io/loadBalancerIPs: 192.168.123.250
spec:
  type: LoadBalancer
  selector:
    app: network-test
  ports:
    - port: 80
      targetPort: 80
