apiVersion: v1
kind: Service
metadata:
  name: lb-test
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test.home.arpa
spec:
  type: LoadBalancer
  selector:
    app: network-test
  ports:
    - port: 80
      targetPort: 80
