apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-shell
spec:
  selector:
    matchLabels:
      app: storage-shell
  template:
    metadata:
      labels:
        app: storage-shell
    spec:
      containers:
      - name: web-shell
        # ttyd is a simple server that shares a terminal over HTTP
        image: tsl0922/ttyd:alpine
        # Start ttyd with a writable shell (-W)
        command: ["ttyd", "-W", "sh"]
        ports:
        - containerPort: 7681
        volumeMounts:
        - name: my-data
          mountPath: "/data"
      volumes:
      - name: my-data
        persistentVolumeClaim:
          claimName: storage-pvc
