apiVersion: v1
kind: Service
metadata:
  name: storage-shell
  annotations:
    metallb.io/loadBalancerIPs: 192.168.123.202
spec:
  type: LoadBalancer
  selector:
    app: storage-shell
  ports:
    - port: 80
      targetPort: 7681
