apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan-pool
spec:
  addresses:
    - 192.168.123.201-192.168.123.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2lb
