apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-test
spec:
  parentRefs:
  - name: gateway
    namespace: istio-system
  hostnames:
    - prometheus.home.arpa
  rules:
    - backendRefs:
        - name: headless
          port: 9090
