apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hypervisor.yaml
  - ./argo-cd/
helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/charts
    version: 82.2.0
    releaseName: kprometheus
    namespace: prometheus
    # https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_
    includeCRDs: true
    valuesFile: values.yaml
