apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # Necessary to fix default values being detected as out of sync
  # https://github.com/argoproj/argo-cd/issues/13004#issuecomment-1650616710
  controller.diff.server.side: "true"
  # Necessary to use Gateway routing
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#prerequisites
  server.insecure: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: "--enable-helm"
