apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-pw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: accounts.argo.password
      remoteRef:
        key: argocd_argo_hash
