apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - metrics.yaml
  - server-metrics.yaml
  - repo-server-metrics.yaml
  - dex-server-metrics.yaml
  - controller-metrics.yaml
  - redis-metrics.yaml
