apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - credentials.yaml
helmCharts:
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    version: 0.15.1
    releaseName: democratic-csi
    namespace: democratic-csi
    valuesFile: values.yaml
